// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facts.sql

package memorydb

import (
	"context"
	"database/sql"
	"time"
)

const insertFact = `-- name: InsertFact :execlastid

INSERT INTO facts(session_id, user_id, text, kind, source_msg_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertFactParams struct {
	SessionID   string
	UserID      sql.NullString
	Text        string
	Kind        string
	SourceMsgID sql.NullInt64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Facts has a regular table + a vec_facts vec0 companion. Per-row vector
// INSERT/DELETE and the cosine-distance RecallFacts query stay raw because
// sqlc cannot parse the vec0 virtual table syntax.
func (q *Queries) InsertFact(ctx context.Context, arg InsertFactParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertFact,
		arg.SessionID,
		arg.UserID,
		arg.Text,
		arg.Kind,
		arg.SourceMsgID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listFacts = `-- name: ListFacts :many
SELECT id, session_id, COALESCE(user_id, '') AS user_id, text, kind,
       COALESCE(source_msg_id, 0) AS source_msg_id, created_at, updated_at
FROM facts
WHERE session_id = ? AND deleted_at IS NULL
ORDER BY updated_at DESC
LIMIT ?
`

type ListFactsParams struct {
	SessionID string
	Limit     int64
}

type ListFactsRow struct {
	ID          int64
	SessionID   string
	UserID      string
	Text        string
	Kind        string
	SourceMsgID int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListFacts(ctx context.Context, arg ListFactsParams) ([]ListFactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFacts, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFactsRow
	for rows.Next() {
		var i ListFactsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.Text,
			&i.Kind,
			&i.SourceMsgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFact = `-- name: SoftDeleteFact :exec
UPDATE facts SET deleted_at = ?
WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteFactParams struct {
	DeletedAt *time.Time
	ID        int64
}

func (q *Queries) SoftDeleteFact(ctx context.Context, arg SoftDeleteFactParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteFact, arg.DeletedAt, arg.ID)
	return err
}

const updateFactText = `-- name: UpdateFactText :execrows
UPDATE facts SET text = ?, updated_at = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateFactTextParams struct {
	Text      string
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) UpdateFactText(ctx context.Context, arg UpdateFactTextParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFactText, arg.Text, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
