// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memories.sql

package memorydb

import (
	"context"
	"database/sql"
	"time"
)

const countMemories = `-- name: CountMemories :one
SELECT COUNT(*) FROM memories
`

func (q *Queries) CountMemories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMemories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertMemory = `-- name: InsertMemory :execlastid

INSERT INTO memories(session_id, text, source_msg_id, created_at)
VALUES (?, ?, ?, ?)
`

type InsertMemoryParams struct {
	SessionID   string
	Text        string
	SourceMsgID sql.NullInt64
	CreatedAt   time.Time
}

// The memories table holds the regular columns (id, session_id, text,
// source_msg_id, created_at). The companion vec_memories virtual table holds
// the embedding column and is queried via raw SQL because sqlc cannot parse
// vec0 syntax. AddMemory in Go does both INSERTs in one transaction.
//
// Recall (cosine-distance search against vec_memories) stays raw.
func (q *Queries) InsertMemory(ctx context.Context, arg InsertMemoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertMemory,
		arg.SessionID,
		arg.Text,
		arg.SourceMsgID,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
