// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package memorydb

import (
	"context"
	"time"
)

const appendMessage = `-- name: AppendMessage :execlastid
INSERT INTO messages(session_id, role, content, token_count, created_at)
VALUES (?, ?, ?, ?, ?)
`

type AppendMessageParams struct {
	SessionID  string
	Role       string
	Content    string
	TokenCount int64
	CreatedAt  time.Time
}

func (q *Queries) AppendMessage(ctx context.Context, arg AppendMessageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, appendMessage,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.TokenCount,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const countMessages = `-- name: CountMessages :one
SELECT COUNT(*) FROM messages
`

func (q *Queries) CountMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const messagesAfter = `-- name: MessagesAfter :many
SELECT id, session_id, role, content, token_count, created_at
FROM messages
WHERE session_id = ? AND id > ?
ORDER BY id DESC
`

type MessagesAfterParams struct {
	SessionID string
	ID        int64
}

// MessagesAfter is used by MaybeSummarize: every message past the
// covers_up_to bound, newest-first so the caller can split by token budget.
func (q *Queries) MessagesAfter(ctx context.Context, arg MessagesAfterParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, messagesAfter, arg.SessionID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.TokenCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesForSession = `-- name: MessagesForSession :many
SELECT id, session_id, role, content, token_count, created_at
FROM messages
WHERE session_id = ?
ORDER BY id DESC
`

// MessagesForSession is used by LoadWindow: ALL messages for a session,
// newest-first. The caller token-budget-trims and reverses.
func (q *Queries) MessagesForSession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, messagesForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.TokenCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
