// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meta.sql

package memorydb

import (
	"context"
	"database/sql"
)

const getMeta = `-- name: GetMeta :one
SELECT value FROM meta WHERE key = ?
`

func (q *Queries) GetMeta(ctx context.Context, key string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getMeta, key)
	var value sql.NullString
	err := row.Scan(&value)
	return value, err
}

const setMeta = `-- name: SetMeta :exec
INSERT INTO meta(key, value) VALUES (?, ?)
`

type SetMetaParams struct {
	Key   string
	Value sql.NullString
}

func (q *Queries) SetMeta(ctx context.Context, arg SetMetaParams) error {
	_, err := q.db.ExecContext(ctx, setMeta, arg.Key, arg.Value)
	return err
}
