// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package memorydb

import (
	"database/sql"
	"time"
)

type Fact struct {
	ID          int64
	SessionID   string
	UserID      sql.NullString
	Text        string
	Kind        string
	SourceMsgID sql.NullInt64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

type Memory struct {
	ID          int64
	SessionID   string
	Text        string
	SourceMsgID sql.NullInt64
	CreatedAt   time.Time
}

type Message struct {
	ID         int64
	SessionID  string
	Role       string
	Content    string
	TokenCount int64
	CreatedAt  time.Time
}

type Meta struct {
	Key   string
	Value sql.NullString
}

type Schedule struct {
	ID       int64
	Name     string
	CronExpr string
	Prompt   string
	Channel  string
	Enabled  int64
	LastRun  *time.Time
}

type Summary struct {
	ID              int64
	SessionID       string
	SummaryText     string
	CoversUpToMsgID int64
	CreatedAt       time.Time
}

type Usage struct {
	ID           int64
	Ts           time.Time
	Provider     sql.NullString
	Model        sql.NullString
	InputTokens  int64
	OutputTokens int64
	Kind         string
}
