// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package memorydb

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AppendMessage(ctx context.Context, arg AppendMessageParams) (int64, error)
	CountMemories(ctx context.Context) (int64, error)
	CountMessages(ctx context.Context) (int64, error)
	GetMeta(ctx context.Context, key string) (sql.NullString, error)
	// Facts has a regular table + a vec_facts vec0 companion. Per-row vector
	// INSERT/DELETE and the cosine-distance RecallFacts query stay raw because
	// sqlc cannot parse the vec0 virtual table syntax.
	InsertFact(ctx context.Context, arg InsertFactParams) (int64, error)
	// The memories table holds the regular columns (id, session_id, text,
	// source_msg_id, created_at). The companion vec_memories virtual table holds
	// the embedding column and is queried via raw SQL because sqlc cannot parse
	// vec0 syntax. AddMemory in Go does both INSERTs in one transaction.
	//
	// Recall (cosine-distance search against vec_memories) stays raw.
	InsertMemory(ctx context.Context, arg InsertMemoryParams) (int64, error)
	InsertSummary(ctx context.Context, arg InsertSummaryParams) error
	// LatestSummary is used by MaybeSummarize: needs both the covers_up_to
	// bound and the prior summary text to chain new content into.
	LatestSummary(ctx context.Context, sessionID string) (LatestSummaryRow, error)
	// LatestSummaryText is used by LoadWindow: just the text of the most
	// recent summary for the session. Returns sql.ErrNoRows when none.
	LatestSummaryText(ctx context.Context, sessionID string) (string, error)
	ListFacts(ctx context.Context, arg ListFactsParams) ([]ListFactsRow, error)
	ListSchedules(ctx context.Context) ([]ListSchedulesRow, error)
	MarkScheduleRun(ctx context.Context, arg MarkScheduleRunParams) (int64, error)
	// MessagesAfter is used by MaybeSummarize: every message past the
	// covers_up_to bound, newest-first so the caller can split by token budget.
	MessagesAfter(ctx context.Context, arg MessagesAfterParams) ([]Message, error)
	// MessagesForSession is used by LoadWindow: ALL messages for a session,
	// newest-first. The caller token-budget-trims and reverses.
	MessagesForSession(ctx context.Context, sessionID string) ([]Message, error)
	RecordUsage(ctx context.Context, arg RecordUsageParams) error
	SetMeta(ctx context.Context, arg SetMetaParams) error
	SoftDeleteFact(ctx context.Context, arg SoftDeleteFactParams) error
	UpdateFactText(ctx context.Context, arg UpdateFactTextParams) (int64, error)
	// UpsertSchedule mirrors UpsertSchedule's ON CONFLICT semantics: replaces
	// cron_expr, prompt, channel, enabled when name matches; otherwise inserts.
	UpsertSchedule(ctx context.Context, arg UpsertScheduleParams) error
	// UsageRollup computes 1d/1w/1m token totals. The window bound is passed as
	// a UTC timestamp; COALESCE keeps the result non-null on empty windows; the
	// CAST AS INTEGER nails the typed return so sqlc doesn't emit interface{}.
	UsageRollup(ctx context.Context, ts time.Time) (UsageRollupRow, error)
}

var _ Querier = (*Queries)(nil)
