// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package memorydb

import (
	"context"
	"time"
)

const listSchedules = `-- name: ListSchedules :many
SELECT name, cron_expr, prompt, channel, enabled
FROM schedules
ORDER BY name
`

type ListSchedulesRow struct {
	Name     string
	CronExpr string
	Prompt   string
	Channel  string
	Enabled  int64
}

func (q *Queries) ListSchedules(ctx context.Context) ([]ListSchedulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulesRow
	for rows.Next() {
		var i ListSchedulesRow
		if err := rows.Scan(
			&i.Name,
			&i.CronExpr,
			&i.Prompt,
			&i.Channel,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScheduleRun = `-- name: MarkScheduleRun :execrows
UPDATE schedules SET last_run = ? WHERE name = ?
`

type MarkScheduleRunParams struct {
	LastRun *time.Time
	Name    string
}

func (q *Queries) MarkScheduleRun(ctx context.Context, arg MarkScheduleRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markScheduleRun, arg.LastRun, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertSchedule = `-- name: UpsertSchedule :exec
INSERT INTO schedules(name, cron_expr, prompt, channel, enabled)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    cron_expr = excluded.cron_expr,
    prompt    = excluded.prompt,
    channel   = excluded.channel,
    enabled   = excluded.enabled
`

type UpsertScheduleParams struct {
	Name     string
	CronExpr string
	Prompt   string
	Channel  string
	Enabled  int64
}

// UpsertSchedule mirrors UpsertSchedule's ON CONFLICT semantics: replaces
// cron_expr, prompt, channel, enabled when name matches; otherwise inserts.
func (q *Queries) UpsertSchedule(ctx context.Context, arg UpsertScheduleParams) error {
	_, err := q.db.ExecContext(ctx, upsertSchedule,
		arg.Name,
		arg.CronExpr,
		arg.Prompt,
		arg.Channel,
		arg.Enabled,
	)
	return err
}
