// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summaries.sql

package memorydb

import (
	"context"
	"time"
)

const insertSummary = `-- name: InsertSummary :exec
INSERT INTO summaries(session_id, summary_text, covers_up_to_msg_id, created_at)
VALUES (?, ?, ?, ?)
`

type InsertSummaryParams struct {
	SessionID       string
	SummaryText     string
	CoversUpToMsgID int64
	CreatedAt       time.Time
}

func (q *Queries) InsertSummary(ctx context.Context, arg InsertSummaryParams) error {
	_, err := q.db.ExecContext(ctx, insertSummary,
		arg.SessionID,
		arg.SummaryText,
		arg.CoversUpToMsgID,
		arg.CreatedAt,
	)
	return err
}

const latestSummary = `-- name: LatestSummary :one
SELECT covers_up_to_msg_id, summary_text FROM summaries
WHERE session_id = ?
ORDER BY id DESC
LIMIT 1
`

type LatestSummaryRow struct {
	CoversUpToMsgID int64
	SummaryText     string
}

// LatestSummary is used by MaybeSummarize: needs both the covers_up_to
// bound and the prior summary text to chain new content into.
func (q *Queries) LatestSummary(ctx context.Context, sessionID string) (LatestSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, latestSummary, sessionID)
	var i LatestSummaryRow
	err := row.Scan(&i.CoversUpToMsgID, &i.SummaryText)
	return i, err
}

const latestSummaryText = `-- name: LatestSummaryText :one
SELECT summary_text FROM summaries
WHERE session_id = ?
ORDER BY id DESC
LIMIT 1
`

// LatestSummaryText is used by LoadWindow: just the text of the most
// recent summary for the session. Returns sql.ErrNoRows when none.
func (q *Queries) LatestSummaryText(ctx context.Context, sessionID string) (string, error) {
	row := q.db.QueryRowContext(ctx, latestSummaryText, sessionID)
	var summary_text string
	err := row.Scan(&summary_text)
	return summary_text, err
}
