// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package memorydb

import (
	"context"
	"database/sql"
	"time"
)

const recordUsage = `-- name: RecordUsage :exec
INSERT INTO usage(ts, provider, model, input_tokens, output_tokens, kind)
VALUES (?, ?, ?, ?, ?, ?)
`

type RecordUsageParams struct {
	Ts           time.Time
	Provider     sql.NullString
	Model        sql.NullString
	InputTokens  int64
	OutputTokens int64
	Kind         string
}

func (q *Queries) RecordUsage(ctx context.Context, arg RecordUsageParams) error {
	_, err := q.db.ExecContext(ctx, recordUsage,
		arg.Ts,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.Kind,
	)
	return err
}

const usageRollup = `-- name: UsageRollup :one
SELECT
    CAST(COALESCE(SUM(input_tokens), 0) AS INTEGER)  AS input_tokens,
    CAST(COALESCE(SUM(output_tokens), 0) AS INTEGER) AS output_tokens
FROM usage
WHERE ts >= ?
`

type UsageRollupRow struct {
	InputTokens  int64
	OutputTokens int64
}

// UsageRollup computes 1d/1w/1m token totals. The window bound is passed as
// a UTC timestamp; COALESCE keeps the result non-null on empty windows; the
// CAST AS INTEGER nails the typed return so sqlc doesn't emit interface{}.
func (q *Queries) UsageRollup(ctx context.Context, ts time.Time) (UsageRollupRow, error) {
	row := q.db.QueryRowContext(ctx, usageRollup, ts)
	var i UsageRollupRow
	err := row.Scan(&i.InputTokens, &i.OutputTokens)
	return i, err
}
